# ---------- Build Stage ----------
    FROM node:20-alpine AS builder

    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install
    
    COPY . .
    
    RUN npm run build
    
    # ---------- Production Stage ----------
    FROM node:20-alpine
    
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install --omit=dev
    
    COPY --from=builder /app/.next ./.next
    COPY --from=builder /app/public ./public
    COPY --from=builder /app/next.config.ts ./
    
    ENV NODE_ENV=production
    
    EXPOSE 3000
    
    CMD ["npm", "start"]